In [17]:
import pandas as pd

df = pd.read_csv('MMG2025_2019-2023_Data_To_Share_County_CSV.csv', encoding='latin-1')

print(df)

        FIPS State            County, State  Year  \
0       1001    AL  Autauga County, Alabama  2019
1       1001    AL  Autauga County, Alabama  2020
2       1001    AL  Autauga County, Alabama  2021
3       1001    AL  Autauga County, Alabama  2022
4       1001    AL  Autauga County, Alabama  2023
...      ...   ...                      ...   ...
15711  56045    WY   Weston County, Wyoming  2019
15712  56045    WY   Weston County, Wyoming  2020
15713  56045    WY   Weston County, Wyoming  2021
15714  56045    WY   Weston County, Wyoming  2022
15715  56045    WY   Weston County, Wyoming  2023

      Overall Food Insecurity Rate # of Food Insecure Persons Overall  \
0                            15.7%                              8,670
1                            14.5%                              8,070
2                            13.3%                              7,770
3                            15.1%                              8,860
4                            15.1%                              8,970
...                            ...                                ...
15711                        12.2%                                860
15712                        11.0%                                760
15713                        10.2%                                710
15714                        13.6%                                940
15715                        13.9%                                950

      Food Insecurity Rate among Black Persons (all ethnicities)  \
0                                                    26%
1                                                    25%
2                                                    23%
3                                                    23%
4                                                    24%
...                                                  ...
15711                                                NaN
15712                                                NaN
15713                                                NaN
15714                                                NaN
15715                                                NaN

      Food Insecurity Rate among Hispanic Persons (any race)  \
0                                                    NaN
1                                                    NaN
2                                                    NaN
3                                                    NaN
4                                                    NaN
...                                                  ...
15711                                                NaN
15712                                                NaN
15713                                                NaN
15714                                                NaN
15715                                                NaN

      Food Insecurity Rate among White, non-Hispanic Persons SNAP Threshold  \
0                                                    12%               130%
1                                                     9%               130%
2                                                     9%               130%
3                                                    11%               130%
4                                                    12%               130%
...                                                  ...                ...
15711                                                12%               130%
15712                                                10%               130%
15713                                                10%               130%
15714                                                12%               130%
15715                                                12%               130%

       ... % food insecure children in HH w/ HH incomes below 185 FPL  \
0      ...                                                69%
1      ...                                                71%
2      ...                                                68%
3      ...                                                68%
4      ...                                                66%
...    ...                                                ...
15711  ...                                                62%
15712  ...                                                50%
15713  ...                                                49%
15714  ...                                                47%
15715  ...                                                41%

      % food insecure children in HH w/ HH incomes above 185 FPL  \
0                                                    31%
1                                                    29%
2                                                    32%
3                                                    32%
4                                                    34%
...                                                  ...
15711                                                38%
15712                                                50%
15713                                                51%
15714                                                53%
15715                                                59%

      Cost Per Meal Weighted weekly $ needed by FI  \
0             $3.00                         $16.88
1             $3.22                         $17.09
2             $3.60                         $20.99
3             $4.01                         $24.86
4             $3.64                         $22.72
...             ...                            ...
15711         $3.21                         $18.07
15712         $3.37                         $17.90
15713         $3.73                         $21.74
15714         $4.13                         $25.57
15715         $3.72                         $23.21

      Weighted Annual Food Budget Shortfall Rural-Urban Continuum Code (2013)  \
0                                $4,439,000                               2.0
1                                $4,184,000                               2.0
2                                $4,947,000                               2.0
3                                $6,680,000                               2.0
4                                $6,183,000                               2.0
...                                     ...                               ...
15711                              $471,000                               7.0
15712                              $413,000                               7.0
15713                              $468,000                               7.0
15714                              $729,000                               7.0
15715                              $669,000                               7.0

      Rural-Urban Continuum Code (2023) Census Region     Census Division  \
0                                   NaN         South  East South Central
1                                   NaN         South  East South Central
2                                   NaN         South  East South Central
3                                   2.0         South  East South Central
4                                   2.0         South  East South Central
...                                 ...           ...                 ...
15711                               NaN          West            Mountain
15712                               NaN          West            Mountain
15713                               NaN          West            Mountain
15714                               9.0          West            Mountain
15715                               9.0          West            Mountain

            FNS Region
0            Southeast
1            Southeast
2            Southeast
3            Southeast
4            Southeast
...                ...
15711  Mountain Plains
15712  Mountain Plains
15713  Mountain Plains
15714  Mountain Plains
15715  Mountain Plains

[15716 rows x 24 columns]

In [ ]:
df.head()

,FIPS,State,"County, State",Year,Overall Food Insecurity Rate,# of Food Insecure Persons Overall,Food Insecurity Rate among Black Persons (all ethnicities),Food Insecurity Rate among Hispanic Persons (any race),"Food Insecurity Rate among White, non-Hispanic Persons",SNAP Threshold,...,% food insecure children in HH w/ HH incomes below 185 FPL,% food insecure children in HH w/ HH incomes above 185 FPL,Cost Per Meal,Weighted weekly $ needed by FI,Weighted Annual Food Budget Shortfall,Rural-Urban Continuum Code (2013),Rural-Urban Continuum Code (2023),Census Region,Census Division,FNS Region
0,1001,AL,"Autauga County, Alabama",2019,15.7%,"8,670",26%,NaN,12%,130%,...,69%,31%,$3.00,$16.88,"$4,439,000",2.0,NaN,South,East South Central,Southeast
1,1001,AL,"Autauga County, Alabama",2020,14.5%,"8,070",25%,NaN,9%,130%,...,71%,29%,$3.22,$17.09,"$4,184,000",2.0,NaN,South,East South Central,Southeast
2,1001,AL,"Autauga County, Alabama",2021,13.3%,"7,770",23%,NaN,9%,130%,...,68%,32%,$3.60,$20.99,"$4,947,000",2.0,NaN,South,East South Central,Southeast
3,1001,AL,"Autauga County, Alabama",2022,15.1%,"8,860",23%,NaN,11%,130%,...,68%,32%,$4.01,$24.86,"$6,680,000",2.0,2.0,South,East South Central,Southeast
4,1001,AL,"Autauga County, Alabama",2023,15.1%,"8,970",24%,NaN,12%,130%,...,66%,34%,$3.64,$22.72,"$6,183,000",2.0,2.0,South,East South Central,Southeast

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15716 entries, 0 to 15715
Data columns (total 24 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   FIPS                                                        15716 non-null  int64
 1   State                                                       15716 non-null  str
 2   County, State                                               15716 non-null  str
 3   Year                                                        15716 non-null  int64
 4   Overall Food Insecurity Rate                                15715 non-null  str
 5   # of Food Insecure Persons Overall                          15715 non-null  str
 6   Food Insecurity Rate among Black Persons (all ethnicities)  7432 non-null   str
 7   Food Insecurity Rate among Hispanic Persons (any race)      8915 non-null   str
 8   Food Insecurity Rate among White, non-Hispanic Persons      15442 non-null  str
 9   SNAP Threshold                                              15716 non-null  str
 10  % FI ? SNAP Threshold                                       15715 non-null  str
 11  % FI > SNAP Threshold                                       15715 non-null  str
 12  Child Food Insecurity Rate                                  15700 non-null  str
 13  # of Food Insecure Children                                 15700 non-null  str
 14  % food insecure children in HH w/ HH incomes below 185 FPL  15692 non-null  str
 15  % food insecure children in HH w/ HH incomes above 185 FPL  15692 non-null  str
 16  Cost Per Meal                                               15716 non-null  str
 17  Weighted weekly $ needed by FI                              15716 non-null  str
 18  Weighted Annual Food Budget Shortfall                       15715 non-null  str
 19  Rural-Urban Continuum Code (2013)                           15694 non-null  float64
 20  Rural-Urban Continuum Code (2023)                           6288 non-null   float64
 21  Census Region                                               15716 non-null  str
 22  Census Division                                             15716 non-null  str
 23  FNS Region                                                  15716 non-null  str
dtypes: float64(2), int64(2), str(20)
memory usage: 2.9 MB

In [ ]:
df.shape

(15716, 24)

In [ ]:
df['County, State'].value_counts()

County, State
Autauga County, Alabama                                   5
Baldwin County, Alabama                                   5
Barbour County, Alabama                                   5
Bibb County, Alabama                                      5
Blount County, Alabama                                    5
                                                         ..
South Central Connecticut Planning Region, Connecticut    2
Southeastern Connecticut Planning Region, Connecticut     2
Western Connecticut Planning Region, Connecticut          2
Doña Ana County, New Mexico                               2
Valdez-Cordova Census Area, Alaska                        1
Name: count, Length: 3154, dtype: int64

In [ ]:
df['State'].value_counts()

State
TX    1270
GA     795
VA     665
KY     600
MO     575
KS     525
IL     510
NC     500
IA     495
TN     475
NE     465
IN     460
OH     440
MN     435
MI     415
MS     410
OK     385
AR     375
WI     360
AL     335
FL     335
PA     335
SD     330
CO     320
LA     320
NY     310
CA     290
MT     280
WV     275
ND     265
SC     230
ID     220
WA     195
OR     180
NM     165
AK     149
UT     145
MD     120
WY     115
NJ     105
NV      85
ME      80
AZ      75
MA      70
VT      70
NH      50
CT      42
HI      25
RI      25
DE      15
DC       5
Name: count, dtype: int64

In [ ]:
df.describe()

,FIPS,Year,Rural-Urban Continuum Code (2013),Rural-Urban Continuum Code (2023)
count,15716.000000,15716.000000,15694.000000,6288.000000
mean,30373.833927,2021.000318,5.011979,5.249046
std,15166.194087,1.414236,2.707610,2.929423
min,1001.000000,2019.000000,1.000000,1.000000
25%,18175.000000,2020.000000,2.000000,2.000000
50%,29175.000000,2021.000000,6.000000,6.000000
75%,45081.000000,2022.000000,7.000000,8.000000
max,56045.000000,2023.000000,9.000000,9.000000

In [ ]:
df.loc[4971:5570]
#Kentucky counties

,FIPS,State,"County, State",Year,Overall Food Insecurity Rate,# of Food Insecure Persons Overall,Food Insecurity Rate among Black Persons (all ethnicities),Food Insecurity Rate among Hispanic Persons (any race),"Food Insecurity Rate among White, non-Hispanic Persons",SNAP Threshold,...,% food insecure children in HH w/ HH incomes below 185 FPL,% food insecure children in HH w/ HH incomes above 185 FPL,Cost Per Meal,Weighted weekly $ needed by FI,Weighted Annual Food Budget Shortfall,Rural-Urban Continuum Code (2013),Rural-Urban Continuum Code (2023),Census Region,Census Division,FNS Region
4971,21001,KY,"Adair County, Kentucky",2019,16.7%,"3,210",20%,NaN,16%,200%,...,78%,22%,$2.78,$15.69,"$1,527,000",7.0,NaN,South,East South Central,Southeast
4972,21001,KY,"Adair County, Kentucky",2020,15.2%,"2,950",17%,NaN,14%,200%,...,79%,21%,$2.79,$14.83,"$1,327,000",7.0,NaN,South,East South Central,Southeast
4973,21001,KY,"Adair County, Kentucky",2021,13.7%,"2,590",NaN,NaN,14%,200%,...,82%,19%,$3.04,$17.69,"$1,390,000",7.0,NaN,South,East South Central,Southeast
4974,21001,KY,"Adair County, Kentucky",2022,18.0%,"3,400",NaN,NaN,17%,200%,...,82%,18%,$3.40,$21.07,"$2,173,000",7.0,7.0,South,East South Central,Southeast
4975,21001,KY,"Adair County, Kentucky",2023,18.5%,"3,530",NaN,NaN,18%,200%,...,89%,11%,$3.16,$19.72,"$2,111,000",7.0,7.0,South,East South Central,Southeast
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5566,21239,KY,"Woodford County, Kentucky",2019,11.2%,"2,960",16%,NaN,12%,200%,...,65%,35%,$3.29,$18.53,"$1,664,000",2.0,NaN,South,East South Central,Southeast
5567,21239,KY,"Woodford County, Kentucky",2020,9.9%,"2,620",18%,NaN,10%,200%,...,74%,26%,$3.32,$17.62,"$1,400,000",2.0,NaN,South,East South Central,Southeast
5568,21239,KY,"Woodford County, Kentucky",2021,8.0%,"2,150",12%,NaN,9%,200%,...,61%,39%,$3.58,$20.83,"$1,358,000",2.0,NaN,South,East South Central,Southeast
5569,21239,KY,"Woodford County, Kentucky",2022,11.7%,"3,150",12%,NaN,11%,200%,...,57%,43%,$4.03,$24.95,"$2,384,000",2.0,2.0,South,East South Central,Southeast
5570,21239,KY,"Woodford County, Kentucky",2023,13.1%,"3,540",17%,NaN,12%,200%,...,61%,39%,$3.66,$22.90,"$2,459,000",2.0,2.0,South,East South Central,Southeast

In [ ]:
df.columns.tolist()

['FIPS',
 'State',
 'County, State',
 'Year',
 'Overall Food Insecurity Rate',
 '# of Food Insecure Persons Overall',
 'Food Insecurity Rate among Black Persons (all ethnicities)',
 'Food Insecurity Rate among Hispanic Persons (any race)',
 'Food Insecurity Rate among White, non-Hispanic Persons',
 'SNAP Threshold',
 '% FI ? SNAP Threshold',
 '% FI > SNAP Threshold',
 'Child Food Insecurity Rate',
 '# of Food Insecure Children',
 '% food insecure children in HH w/ HH incomes below 185 FPL',
 '% food insecure children in HH w/ HH incomes above 185 FPL',
 'Cost Per Meal',
 'Weighted weekly $ needed by FI',
 'Weighted Annual Food Budget Shortfall',
 'Rural-Urban Continuum Code (2013)',
 'Rural-Urban Continuum Code (2023)',
 'Census Region',
 'Census Division',
 'FNS Region']

In [ ]:
df.iloc[0:3, 0:2]

   FIPS State
0  1001    AL
1  1001    AL
2  1001    AL

In [ ]:
df.sort_values(by=['Overall Food Insecurity Rate'], ascending=[True])

,FIPS,State,"County, State",Year,Overall Food Insecurity Rate,# of Food Insecure Persons Overall,Food Insecurity Rate among Black Persons (all ethnicities),Food Insecurity Rate among Hispanic Persons (any race),"Food Insecurity Rate among White, non-Hispanic Persons",SNAP Threshold,...,% food insecure children in HH w/ HH incomes below 185 FPL,% food insecure children in HH w/ HH incomes above 185 FPL,Cost Per Meal,Weighted weekly $ needed by FI,Weighted Annual Food Budget Shortfall,Rural-Urban Continuum Code (2013),Rural-Urban Continuum Code (2023),Census Region,Census Division,FNS Region
2363,13171,GA,"Lamar County, Georgia",2021,10.0%,"1,850",16%,NaN,9%,130%,...,100%,0%,$3.11,$18.10,"$1,016,000",1.0,NaN,South,South Atlantic,Southeast
4409,19183,IA,"Washington County, Iowa",2022,10.0%,"2,260",NaN,16%,9%,160%,...,70%,30%,$3.82,$23.66,"$1,622,000",3.0,3.0,Midwest,West North Central,Midwest
10039,38033,ND,"Golden Valley County, North Dakota",2022,10.0%,170,NaN,NaN,8%,200%,...,72%,28%,$4.13,$25.60,"$132,000",9.0,9.0,Midwest,West North Central,Mountain Plains
8688,31165,NE,"Sioux County, Nebraska",2021,10.0%,110,NaN,NaN,9%,165%,...,100%,0%,$3.43,$19.99,"$67,000",9.0,NaN,Midwest,West North Central,Mountain Plains
1354,8051,CO,"Gunnison County, Colorado",2019,10.0%,"1,680",NaN,17%,10%,200%,...,96%,5%,$3.59,$20.21,"$1,030,000",7.0,NaN,West,Mountain,Mountain Plains
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3350,17147,IL,"Piatt County, Illinois",2023,9.9%,"1,650",NaN,NaN,8%,165%,...,56%,44%,$3.63,$22.71,"$1,137,000",3.0,3.0,Midwest,East North Central,Midwest
14139,51013,VA,"Arlington County, Virginia",2022,9.9%,"23,390",24%,17%,6%,200%,...,91%,9%,$5.52,$34.23,"$24,287,000",1.0,1.0,South,South Atlantic,Mid-Atlantic
1269,8017,CO,"Cheyenne County, Colorado",2019,9.9%,200,NaN,NaN,10%,200%,...,86%,14%,$3.01,$16.96,"$103,000",9.0,NaN,West,Mountain,Mountain Plains
8188,30077,MT,"Powell County, Montana",2021,9.9%,690,NaN,NaN,9%,200%,...,71%,30%,$3.70,$21.52,"$451,000",6.0,NaN,West,Mountain,Mountain Plains
2750,15005,HI,"Kalawao County, Hawaii",2023,NaN,NaN,NaN,NaN,NaN,200%,...,NaN,NaN,$5.29,$33.07,NaN,3.0,3.0,West,Pacific,Western

['State',
 'County, State',
 'Year',
 'Overall Food Insecurity Rate',
 '# of Food Insecure Persons Overall',
 'Food Insecurity Rate among Black Persons (all ethnicities)',
 'Food Insecurity Rate among Hispanic Persons (any race)',
 'Food Insecurity Rate among White, non-Hispanic Persons',
 'SNAP Threshold',
 '% FI ? SNAP Threshold',
 '% FI > SNAP Threshold',
 'Child Food Insecurity Rate',
 '# of Food Insecure Children',
 '% food insecure children in HH w/ HH incomes below 185 FPL',
 '% food insecure children in HH w/ HH incomes above 185 FPL',
 'Cost Per Meal',
 'Weighted weekly $ needed by FI',
 'Weighted Annual Food Budget Shortfall',
 'Rural-Urban Continuum Code (2013)',
 'Rural-Urban Continuum Code (2023)',
 'Census Region',
 'Census Division',
 'FNS Region']

In [64]:
df.drop('FIPS', axis='columns')

,State,"County, State",Year,Overall Food Insecurity Rate,# of Food Insecure Persons Overall,Food Insecurity Rate among Black Persons (all ethnicities),Food Insecurity Rate among Hispanic Persons (any race),"Food Insecurity Rate among White, non-Hispanic Persons",SNAP Threshold,% FI ? SNAP Threshold,...,% food insecure children in HH w/ HH incomes below 185 FPL,% food insecure children in HH w/ HH incomes above 185 FPL,Cost Per Meal,Weighted weekly $ needed by FI,Weighted Annual Food Budget Shortfall,Rural-Urban Continuum Code (2013),Rural-Urban Continuum Code (2023),Census Region,Census Division,FNS Region
0,AL,"Autauga County, Alabama",2019,15.7%,8670,26%,NaN,12%,130%,49%,...,69%,31%,$3.00,$16.88,"$4,439,000",2.0,NaN,South,East South Central,Southeast
1,AL,"Autauga County, Alabama",2020,14.5%,8070,25%,NaN,9%,130%,48%,...,71%,29%,$3.22,$17.09,"$4,184,000",2.0,NaN,South,East South Central,Southeast
2,AL,"Autauga County, Alabama",2021,13.3%,7770,23%,NaN,9%,130%,48%,...,68%,32%,$3.60,$20.99,"$4,947,000",2.0,NaN,South,East South Central,Southeast
3,AL,"Autauga County, Alabama",2022,15.1%,8860,23%,NaN,11%,130%,44%,...,68%,32%,$4.01,$24.86,"$6,680,000",2.0,2.0,South,East South Central,Southeast
4,AL,"Autauga County, Alabama",2023,15.1%,8970,24%,NaN,12%,130%,43%,...,66%,34%,$3.64,$22.72,"$6,183,000",2.0,2.0,South,East South Central,Southeast
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15711,WY,"Weston County, Wyoming",2019,12.2%,860,NaN,NaN,12%,130%,48%,...,62%,38%,$3.21,$18.07,"$471,000",7.0,NaN,West,Mountain,Mountain Plains
15712,WY,"Weston County, Wyoming",2020,11.0%,760,NaN,NaN,10%,130%,49%,...,50%,50%,$3.37,$17.90,"$413,000",7.0,NaN,West,Mountain,Mountain Plains
15713,WY,"Weston County, Wyoming",2021,10.2%,710,NaN,NaN,10%,130%,47%,...,49%,51%,$3.73,$21.74,"$468,000",7.0,NaN,West,Mountain,Mountain Plains
15714,WY,"Weston County, Wyoming",2022,13.6%,940,NaN,NaN,12%,130%,38%,...,47%,53%,$4.13,$25.57,"$729,000",7.0,9.0,West,Mountain,Mountain Plains
15715,WY,"Weston County, Wyoming",2023,13.9%,950,NaN,NaN,12%,130%,36%,...,41%,59%,$3.72,$23.21,"$669,000",7.0,9.0,West,Mountain,Mountain Plains

In [65]:
df.dtypes

FIPS                                                            int64
State                                                             str
County, State                                                     str
Year                                                            int64
Overall Food Insecurity Rate                                      str
# of Food Insecure Persons Overall                              Int64
Food Insecurity Rate among Black Persons (all ethnicities)        str
Food Insecurity Rate among Hispanic Persons (any race)            str
Food Insecurity Rate among White, non-Hispanic Persons            str
SNAP Threshold                                                    str
% FI ? SNAP Threshold                                             str
% FI > SNAP Threshold                                             str
Child Food Insecurity Rate                                        str
# of Food Insecure Children                                     Int64
% food insecure children in HH w/ HH incomes below 185 FPL        str
% food insecure children in HH w/ HH incomes above 185 FPL        str
Cost Per Meal                                                     str
Weighted weekly $ needed by FI                                    str
Weighted Annual Food Budget Shortfall                             str
Rural-Urban Continuum Code (2013)                             float64
Rural-Urban Continuum Code (2023)                             float64
Census Region                                                     str
Census Division                                                   str
FNS Region                                                        str
dtype: object

In [ ]:
df.isna()

,FIPS,State,"County, State",Year,Overall Food Insecurity Rate,# of Food Insecure Persons Overall,Food Insecurity Rate among Black Persons (all ethnicities),Food Insecurity Rate among Hispanic Persons (any race),"Food Insecurity Rate among White, non-Hispanic Persons",SNAP Threshold,...,% food insecure children in HH w/ HH incomes below 185 FPL,% food insecure children in HH w/ HH incomes above 185 FPL,Cost Per Meal,Weighted weekly $ needed by FI,Weighted Annual Food Budget Shortfall,Rural-Urban Continuum Code (2013),Rural-Urban Continuum Code (2023),Census Region,Census Division,FNS Region
0,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,True,False,False,False
2,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15711,False,False,False,False,False,False,True,True,False,False,...,False,False,False,False,False,False,True,False,False,False
15712,False,False,False,False,False,False,True,True,False,False,...,False,False,False,False,False,False,True,False,False,False
15713,False,False,False,False,False,False,True,True,False,False,...,False,False,False,False,False,False,True,False,False,False
15714,False,False,False,False,False,False,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False
15715,False,False,False,False,False,False,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull()

,FIPS,State,"County, State",Year,Overall Food Insecurity Rate,# of Food Insecure Persons Overall,Food Insecurity Rate among Black Persons (all ethnicities),Food Insecurity Rate among Hispanic Persons (any race),"Food Insecurity Rate among White, non-Hispanic Persons",SNAP Threshold,...,% food insecure children in HH w/ HH incomes below 185 FPL,% food insecure children in HH w/ HH incomes above 185 FPL,Cost Per Meal,Weighted weekly $ needed by FI,Weighted Annual Food Budget Shortfall,Rural-Urban Continuum Code (2013),Rural-Urban Continuum Code (2023),Census Region,Census Division,FNS Region
0,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,True,False,False,False
2,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15711,False,False,False,False,False,False,True,True,False,False,...,False,False,False,False,False,False,True,False,False,False
15712,False,False,False,False,False,False,True,True,False,False,...,False,False,False,False,False,False,True,False,False,False
15713,False,False,False,False,False,False,True,True,False,False,...,False,False,False,False,False,False,True,False,False,False
15714,False,False,False,False,False,False,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False
15715,False,False,False,False,False,False,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False

In [33]:
null_rows = df[df['# of Food Insecure Persons Overall'].isnull()]
print(null_rows)

       FIPS State           County, State  Year Overall Food Insecurity Rate  \
2750  15005    HI  Kalawao County, Hawaii  2023                          NaN

     # of Food Insecure Persons Overall  \
2750                                NaN

     Food Insecurity Rate among Black Persons (all ethnicities)  \
2750                                                NaN

     Food Insecurity Rate among Hispanic Persons (any race)  \
2750                                                NaN

     Food Insecurity Rate among White, non-Hispanic Persons SNAP Threshold  \
2750                                                NaN               200%

      ... % food insecure children in HH w/ HH incomes below 185 FPL  \
2750  ...                                                NaN

     % food insecure children in HH w/ HH incomes above 185 FPL Cost Per Meal  \
2750                                                NaN                 $5.29

     Weighted weekly $ needed by FI Weighted Annual Food Budget Shortfall  \
2750                         $33.07                                   NaN

     Rural-Urban Continuum Code (2013) Rural-Urban Continuum Code (2023)  \
2750                               3.0                               3.0

     Census Region Census Division  FNS Region
2750          West         Pacific     Western

[1 rows x 24 columns]

In [35]:
null_rows = df[df['# of Food Insecure Children'].isnull()]
print(null_rows)

        FIPS State                  County, State  Year  \
1363    8053    CO      Hinsdale County, Colorado  2023
2750   15005    HI         Kalawao County, Hawaii  2023
8170   30069    MT      Petroleum County, Montana  2023
8505   31091    NE        Hooker County, Nebraska  2023
8565   31115    NE          Loup County, Nebraska  2023
8705   31171    NE        Thomas County, Nebraska  2023
9975   38007    ND  Billings County, North Dakota  2023
12885  48105    TX         Crockett County, Texas  2023
13275  48261    TX           Kenedy County, Texas  2023
13280  48263    TX             Kent County, Texas  2023
13295  48269    TX             King County, Texas  2023
13300  48271    TX           Kinney County, Texas  2023
13375  48301    TX           Loving County, Texas  2023
13420  48319    TX            Mason County, Texas  2023
13700  48431    TX         Sterling County, Texas  2023
13730  48443    TX          Terrell County, Texas  2023

      Overall Food Insecurity Rate # of Food Insecure Persons Overall  \
1363                          9.9%                                 90
2750                           NaN                                NaN
8170                          8.8%                                 40
8505                         15.6%                                100
8565                         14.3%                                 80
8705                         12.1%                                 80
9975                          9.4%                                 90
12885                        14.4%                                410
13275                        26.4%                                 10
13280                        17.0%                                120
13295                        19.9%                                 40
13300                        20.4%                                640
13375                        24.9%                                 10
13420                        15.9%                                630
13700                        12.7%                                180
13730                        16.4%                                140

      Food Insecurity Rate among Black Persons (all ethnicities)  \
1363                                                 NaN
2750                                                 NaN
8170                                                 NaN
8505                                                 NaN
8565                                                 NaN
8705                                                 NaN
9975                                                 NaN
12885                                                NaN
13275                                                NaN
13280                                                NaN
13295                                                NaN
13300                                                NaN
13375                                                NaN
13420                                                NaN
13700                                                NaN
13730                                                NaN

      Food Insecurity Rate among Hispanic Persons (any race)  \
1363                                                 NaN
2750                                                 NaN
8170                                                 NaN
8505                                                 NaN
8565                                                 NaN
8705                                                 NaN
9975                                                 NaN
12885                                                NaN
13275                                                NaN
13280                                                NaN
13295                                                NaN
13300                                                23%
13375                                                NaN
13420                                                31%
13700                                                NaN
13730                                                NaN

      Food Insecurity Rate among White, non-Hispanic Persons SNAP Threshold  \
1363                                                  8%               200%
2750                                                 NaN               200%
8170                                                 NaN               200%
8505                                                 14%               165%
8565                                                 NaN               165%
8705                                                 10%               165%
9975                                                  7%               200%
12885                                                13%               165%
13275                                                NaN               165%
13280                                                12%               165%
13295                                                NaN               165%
13300                                                14%               165%
13375                                                NaN               165%
13420                                                 9%               165%
13700                                                 7%               165%
13730                                                NaN               165%

       ... % food insecure children in HH w/ HH incomes below 185 FPL  \
1363   ...                                                NaN
2750   ...                                                NaN
8170   ...                                                NaN
8505   ...                                                NaN
8565   ...                                                NaN
8705   ...                                                NaN
9975   ...                                                NaN
12885  ...                                                NaN
13275  ...                                                NaN
13280  ...                                                NaN
13295  ...                                                NaN
13300  ...                                                NaN
13375  ...                                                NaN
13420  ...                                                NaN
13700  ...                                                NaN
13730  ...                                                NaN

      % food insecure children in HH w/ HH incomes above 185 FPL  \
1363                                                 NaN
2750                                                 NaN
8170                                                 NaN
8505                                                 NaN
8565                                                 NaN
8705                                                 NaN
9975                                                 NaN
12885                                                NaN
13275                                                NaN
13280                                                NaN
13295                                                NaN
13300                                                NaN
13375                                                NaN
13420                                                NaN
13700                                                NaN
13730                                                NaN

      Cost Per Meal Weighted weekly $ needed by FI  \
1363          $4.10                         $25.60
2750          $5.29                         $33.07
8170          $3.65                         $22.84
8505          $3.45                         $21.55
8565          $3.21                         $20.04
8705          $3.45                         $21.55
9975          $3.72                         $23.26
12885         $3.09                         $19.30
13275         $3.17                         $19.79
13280         $3.36                         $20.99
13295         $3.36                         $20.99
13300         $2.84                         $17.72
13375         $3.50                         $21.89
13420         $3.02                         $18.88
13700         $3.10                         $19.37
13730         $2.84                         $17.72

      Weighted Annual Food Budget Shortfall Rural-Urban Continuum Code (2013)  \
1363                                $70,000                               9.0
2750                                    NaN                               3.0
8170                                $28,000                               9.0
8505                                $65,000                               9.0
8565                                $49,000                               9.0
8705                                $52,000                               9.0
9975                                $63,000                               9.0
12885                              $240,000                               7.0
13275                                $6,000                               9.0
13280                               $76,000                               9.0
13295                               $25,000                               9.0
13300                              $344,000                               7.0
13375                                $7,000                               9.0
13420                              $361,000                               9.0
13700                              $106,000                               8.0
13730                               $75,000                               9.0

      Rural-Urban Continuum Code (2023) Census Region     Census Division  \
1363                                9.0          West            Mountain
2750                                3.0          West             Pacific
8170                                9.0          West            Mountain
8505                                9.0       Midwest  West North Central
8565                                9.0       Midwest  West North Central
8705                                9.0       Midwest  West North Central
9975                                9.0       Midwest  West North Central
12885                               8.0         South  West South Central
13275                               9.0         South  West South Central
13280                               9.0         South  West South Central
13295                               9.0         South  West South Central
13300                               9.0         South  West South Central
13375                               9.0         South  West South Central
13420                               9.0         South  West South Central
13700                               8.0         South  West South Central
13730                               9.0         South  West South Central

            FNS Region
1363   Mountain Plains
2750           Western
8170   Mountain Plains
8505   Mountain Plains
8565   Mountain Plains
8705   Mountain Plains
9975   Mountain Plains
12885        Southwest
13275        Southwest
13280        Southwest
13295        Southwest
13300        Southwest
13375        Southwest
13420        Southwest
13700        Southwest
13730        Southwest

[16 rows x 24 columns]

In [ ]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
15711    False
15712    False
15713    False
15714    False
15715    False
Length: 15716, dtype: bool

In [ ]:
duplicates = df[df.duplicated()]
print(duplicates)
#This means there are no duplicates

Empty DataFrame
Columns: [FIPS, State, County, State, Year, Overall Food Insecurity Rate, # of Food Insecure Persons Overall, Food Insecurity Rate among Black Persons (all ethnicities), Food Insecurity Rate among Hispanic Persons (any race), Food Insecurity Rate among White, non-Hispanic Persons, SNAP Threshold, % FI ? SNAP Threshold, % FI > SNAP Threshold, Child Food Insecurity Rate, # of Food Insecure Children, % food insecure children in HH w/ HH incomes below 185 FPL, % food insecure children in HH w/ HH incomes above 185 FPL, Cost Per Meal, Weighted weekly $ needed by FI, Weighted Annual Food Budget Shortfall, Rural-Urban Continuum Code (2013), Rural-Urban Continuum Code (2023), Census Region, Census Division, FNS Region]
Index: []

[0 rows x 24 columns]

In [ ]:
df['# of Food Insecure Persons Overall'].dtype

Removed commas from numerical values, changed those values from strings to integers

In [ ]:
#ser = pd.Series(df['# of Food Insecure Persons Overall']).head().strip()
#pd.to_numeric(ser)
#ser
#avg = df['# of Food Insecure Persons Overall'].mean()
#print(avg)

df['# of Food Insecure Persons Overall'] = df['# of Food Insecure Persons Overall'].str.replace(',', '')

df['# of Food Insecure Persons Overall'] = df['# of Food Insecure Persons Overall'].astype('Int64')

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15716 entries, 0 to 15715
Data columns (total 24 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   FIPS                                                        15716 non-null  int64
 1   State                                                       15716 non-null  str
 2   County, State                                               15716 non-null  str
 3   Year                                                        15716 non-null  int64
 4   Overall Food Insecurity Rate                                15715 non-null  str
 5   # of Food Insecure Persons Overall                          15715 non-null  Int64
 6   Food Insecurity Rate among Black Persons (all ethnicities)  7432 non-null   str
 7   Food Insecurity Rate among Hispanic Persons (any race)      8915 non-null   str
 8   Food Insecurity Rate among White, non-Hispanic Persons      15442 non-null  str
 9   SNAP Threshold                                              15716 non-null  str
 10  % FI ? SNAP Threshold                                       15715 non-null  str
 11  % FI > SNAP Threshold                                       15715 non-null  str
 12  Child Food Insecurity Rate                                  15700 non-null  str
 13  # of Food Insecure Children                                 15715 non-null  str
 14  % food insecure children in HH w/ HH incomes below 185 FPL  15692 non-null  str
 15  % food insecure children in HH w/ HH incomes above 185 FPL  15692 non-null  str
 16  Cost Per Meal                                               15716 non-null  str
 17  Weighted weekly $ needed by FI                              15716 non-null  str
 18  Weighted Annual Food Budget Shortfall                       15715 non-null  str
 19  Rural-Urban Continuum Code (2013)                           15694 non-null  float64
 20  Rural-Urban Continuum Code (2023)                           6288 non-null   float64
 21  Census Region                                               15716 non-null  str
 22  Census Division                                             15716 non-null  str
 23  FNS Region                                                  15716 non-null  str
dtypes: Int64(1), float64(2), int64(2), str(19)
memory usage: 2.9 MB

Removed commas from numerical values, changed those values from strings to integers

In [63]:
#ser = pd.Series(df['# of Food Insecure Persons Overall']).head().strip()
#pd.to_numeric(ser)
#ser

#avg = df['# of Food Insecure Persons Overall'].mean()
#print(avg)

df['# of Food Insecure Children'] = df['# of Food Insecure Children'].str.replace(',', '')

df['# of Food Insecure Children'] = df['# of Food Insecure Children'].astype('Int64')

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15716 entries, 0 to 15715
Data columns (total 24 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   FIPS                                                        15716 non-null  int64
 1   State                                                       15716 non-null  str
 2   County, State                                               15716 non-null  str
 3   Year                                                        15716 non-null  int64
 4   Overall Food Insecurity Rate                                15715 non-null  str
 5   # of Food Insecure Persons Overall                          15715 non-null  Int64
 6   Food Insecurity Rate among Black Persons (all ethnicities)  7432 non-null   str
 7   Food Insecurity Rate among Hispanic Persons (any race)      8915 non-null   str
 8   Food Insecurity Rate among White, non-Hispanic Persons      15442 non-null  str
 9   SNAP Threshold                                              15716 non-null  str
 10  % FI ? SNAP Threshold                                       15715 non-null  str
 11  % FI > SNAP Threshold                                       15715 non-null  str
 12  Child Food Insecurity Rate                                  15700 non-null  str
 13  # of Food Insecure Children                                 15715 non-null  Int64
 14  % food insecure children in HH w/ HH incomes below 185 FPL  15692 non-null  str
 15  % food insecure children in HH w/ HH incomes above 185 FPL  15692 non-null  str
 16  Cost Per Meal                                               15716 non-null  str
 17  Weighted weekly $ needed by FI                              15716 non-null  str
 18  Weighted Annual Food Budget Shortfall                       15715 non-null  str
 19  Rural-Urban Continuum Code (2013)                           15694 non-null  float64
 20  Rural-Urban Continuum Code (2023)                           6288 non-null   float64
 21  Census Region                                               15716 non-null  str
 22  Census Division                                             15716 non-null  str
 23  FNS Region                                                  15716 non-null  str
dtypes: Int64(2), float64(2), int64(2), str(18)
memory usage: 2.9 MB

In [58]:
df.dtypes

FIPS                                                            int64
State                                                             str
County, State                                                     str
Year                                                            int64
Overall Food Insecurity Rate                                      str
# of Food Insecure Persons Overall                                str
Food Insecurity Rate among Black Persons (all ethnicities)        str
Food Insecurity Rate among Hispanic Persons (any race)            str
Food Insecurity Rate among White, non-Hispanic Persons            str
SNAP Threshold                                                    str
% FI ? SNAP Threshold                                             str
% FI > SNAP Threshold                                             str
Child Food Insecurity Rate                                        str
# of Food Insecure Children                                       str
% food insecure children in HH w/ HH incomes below 185 FPL        str
% food insecure children in HH w/ HH incomes above 185 FPL        str
Cost Per Meal                                                     str
Weighted weekly $ needed by FI                                    str
Weighted Annual Food Budget Shortfall                             str
Rural-Urban Continuum Code (2013)                             float64
Rural-Urban Continuum Code (2023)                             float64
Census Region                                                     str
Census Division                                                   str
FNS Region                                                        str
dtype: object

Renamed columns for better readability.

In [92]:
df.rename(columns={'Overal FI Rate': 'Overall FI Rate',
                   '# of Food Insecure Persons Overall': '# FI Persons Overall',
                   'Food Insecurity Rate among Black Persons (all ethnicities)': 'FI Rate Blk (all ethn)',
                   'Food Insecurity Rate among Hispanic Persons (any race)': 'FI Hsp (any race)',
                   'Food Insecurity Rate among White, non-Hispanic Persons': 'FI Rate Wht, non-Hsp',
                   'SNAP Threshold': 'SNAP Thresh.', 
                   '% food insecure children in HH w/ HH incomes below 185 FPL': '% FI Children HH w/$ < 185 FPL',
                   '% food insecure children in HH w/ HH incomes above 185 FPL': '% FI Children HH w/$ > 185 FPL',
                   'Child Food Insecurity Rate': 'Child FI Rate',
                   '# of Food Insecure Children': '# FI Children',
                   'Cost Per Meal': '$ Per Meal',
                   'Weighted weekly $ needed by FI': 'Wghtd Wkly $ Needed by FI',
                   'Weighted Annual Food Budget Shortfall': 'Wghtd Annual Food Budg Shortfall',
                   'Rural-Urban Continuum Code (2013)': 'Rur-Urb Cont. Code (2013)',
                   'Rural-Urban Continuum Code (2023)': 'Rur-Urb Cont. Code (2023)',
                   'Census Region': 'Census Reg.',
                   'Census Division': 'Census Div.',
                   'FNS Region': 'FNS Reg.'
                   }, inplace=True)
df

,FIPS,State,"County, State",Year,Overall FI Rate,# FI Persons Overall,FI Rate Blk (all ethn),FI Hsp (any race),"FI Rate Wht, non-Hsp",SNAP Thresh.,...,% FI Children HH w/$ < 185 FPL,% FI Children HH w/$ > 185 FPL,$ Per Meal,Wghtd Wkly $ Needed by FI,Wghtd Annual Food Budg Shortfall,R-U Cont. Code (2013),R-U Cont. Code (2023),Census Reg.,Census Div.,FNS Reg.
0,1001,AL,"Autauga County, Alabama",2019,15.7%,8670,26%,NaN,12%,130%,...,69%,31%,$3.00,$16.88,"$4,439,000",2.0,NaN,South,East South Central,Southeast
1,1001,AL,"Autauga County, Alabama",2020,14.5%,8070,25%,NaN,9%,130%,...,71%,29%,$3.22,$17.09,"$4,184,000",2.0,NaN,South,East South Central,Southeast
2,1001,AL,"Autauga County, Alabama",2021,13.3%,7770,23%,NaN,9%,130%,...,68%,32%,$3.60,$20.99,"$4,947,000",2.0,NaN,South,East South Central,Southeast
3,1001,AL,"Autauga County, Alabama",2022,15.1%,8860,23%,NaN,11%,130%,...,68%,32%,$4.01,$24.86,"$6,680,000",2.0,2.0,South,East South Central,Southeast
4,1001,AL,"Autauga County, Alabama",2023,15.1%,8970,24%,NaN,12%,130%,...,66%,34%,$3.64,$22.72,"$6,183,000",2.0,2.0,South,East South Central,Southeast
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15711,56045,WY,"Weston County, Wyoming",2019,12.2%,860,NaN,NaN,12%,130%,...,62%,38%,$3.21,$18.07,"$471,000",7.0,NaN,West,Mountain,Mountain Plains
15712,56045,WY,"Weston County, Wyoming",2020,11.0%,760,NaN,NaN,10%,130%,...,50%,50%,$3.37,$17.90,"$413,000",7.0,NaN,West,Mountain,Mountain Plains
15713,56045,WY,"Weston County, Wyoming",2021,10.2%,710,NaN,NaN,10%,130%,...,49%,51%,$3.73,$21.74,"$468,000",7.0,NaN,West,Mountain,Mountain Plains
15714,56045,WY,"Weston County, Wyoming",2022,13.6%,940,NaN,NaN,12%,130%,...,47%,53%,$4.13,$25.57,"$729,000",7.0,9.0,West,Mountain,Mountain Plains
15715,56045,WY,"Weston County, Wyoming",2023,13.9%,950,NaN,NaN,12%,130%,...,41%,59%,$3.72,$23.21,"$669,000",7.0,9.0,West,Mountain,Mountain Plains

In [93]:
df.dtypes

FIPS                                  int64
State                                   str
County, State                           str
Year                                  int64
Overall FI Rate                         str
# FI Persons Overall                  Int64
FI Rate Blk (all ethn)                  str
FI Hsp (any race)                       str
FI Rate Wht, non-Hsp                    str
SNAP Thresh.                            str
% FI ? SNAP Threshold                   str
% FI > SNAP Threshold                   str
Child FI Rate                           str
# FI Children                         Int64
% FI Children HH w/$ < 185 FPL          str
% FI Children HH w/$ > 185 FPL          str
$ Per Meal                              str
Wghtd Wkly $ Needed by FI               str
Wghtd Annual Food Budg Shortfall        str
R-U Cont. Code (2013)               float64
R-U Cont. Code (2023)               float64
Census Reg.                             str
Census Div.                             str
FNS Reg.                                str
dtype: object

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15716 entries, 0 to 15715
Data columns (total 23 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   State                             15716 non-null  str
 1   County, State                     15716 non-null  str
 2   Year                              15716 non-null  int64
 3   Overall FI Rate                   15715 non-null  str
 4   # FI Persons Overall              15715 non-null  Int64
 5   FI Rate Blk (all ethn)            7432 non-null   str
 6   FI Hsp (any race)                 8915 non-null   str
 7   FI Rate Wht, non-Hsp              15442 non-null  str
 8   SNAP Thresh.                      15716 non-null  str
 9   % FI ? SNAP Threshold             15715 non-null  str
 10  % FI > SNAP Threshold             15715 non-null  str
 11  Child FI Rate                     15700 non-null  str
 12  # FI Children                     15715 non-null  Int64
 13  % FI Children HH w/$ < 185 FPL    15692 non-null  str
 14  % FI Children HH w/$ > 185 FPL    15692 non-null  str
 15  $ Per Meal                        15716 non-null  str
 16  Wghtd Wkly $ Needed by FI         15716 non-null  str
 17  Wghtd Annual Food Budg Shortfall  15715 non-null  str
 18  R-U Cont. Code (2013)             15694 non-null  float64
 19  R-U Cont. Code (2023)             6288 non-null   float64
 20  Census Reg.                       15716 non-null  str
 21  Census Div.                       15716 non-null  str
 22  FNS Reg.                          15716 non-null  str
dtypes: Int64(2), float64(2), int64(1), str(18)
memory usage: 2.8 MB

In [ ]:
df.describe()
# Count = the number of values in each column

,Year,# FI Persons Overall,# FI Children,R-U Cont. Code (2013),R-U Cont. Code (2023)
count,15716.000000,15715.0,15715.0,15694.000000,6288.000000
mean,2021.000318,12590.080178,12590.080178,5.011979,5.249046
std,1.414236,40950.866318,40950.866318,2.707610,2.929423
min,2019.000000,10.0,10.0,1.000000,1.000000
25%,2020.000000,1470.0,1470.0,2.000000,2.000000
50%,2021.000000,3570.0,3570.0,6.000000,6.000000
75%,2022.000000,8980.0,8980.0,7.000000,8.000000
max,2023.000000,1436270.0,1436270.0,9.000000,9.000000

Next steps: 
1. Figure out what to do with all of the NaN values.
2. Grouping and aggregating with .groupby()
3. Try grouping by years, filtering for specific years.
4. Sorting to find highest/lowest values or interesting outliers
5. Creating small summary tables that help answer early questions

Start noting:
1. Surprises or unusual patterns
2. Gaps or limitations in the data
3. Trends worth visualizing
4. Questions that feel worth digging into

Possible questions/analyses:
1. Compare trends over time (e.g., 2018 to 2023)
2. Compare states, regions
3. Compare counties within states 

Create at least: 
1. One chart that shows a distribution (e.g., histogram, boxplot)
2. One chart that shows a comparison (e.g., bar chart, grouped bar, count plot)
3. One chart that shows a relationship or pattern (e.g., line chart, scatterplot)

Consider (write down) these questions (that you will later add as markdown cells):
1. What question were you exploring?
2. What made you choose this type of chart?
3. What does the chart help you notice?